name: Check for new description edits
on:
  schedule:
    - cron: "*/5 * * * *"
  
  workflow_dispatch:

jobs:
  check:
    name: Check for new description changes
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 14.x
        
      - name: Check for new description changes
        run: node src/index.js
        
      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update files
          commit_user_name: autotable[bot]
          commit_user_email: autotable[bot]@users.noreply.github.com
